# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d586d816dba6aae7788ccaf133feaff"
name = "Premier-WishList"
application_url = "https://carrying-remained-clay-vegetable.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://carrying-remained-clay-vegetable.trycloudflare.com/api/auth"
]
